version: '3.9'
services: 
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        ports: 
            - 3000:3000
        volumes:
            - ./client/src:/mafioso/client/src
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - 4000:4000
        volumes:
            - ./server/src:/mafioso/server/src
