# Common file. Required for any build.

version: '3.9'
services:
    redis:
        image: 'redis:alpine'
    web: 
        build: .
        environment:
            REDIS_HOST: redis
        ports:
            - 3000:3000
        depends_on: 
            - redis