version: '3.9'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        ports:
            - 3000:80
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        ports:
            - 4000:4000